const { forwardTo } = require("prisma-binding");

const Query = {
  doors: forwardTo("db"),
  doorCollections: forwardTo("db"),
  doorLines: forwardTo("db"),
  frameProfiles: forwardTo("db"),
  sidelites: forwardTo("db"),
  styleShapes: forwardTo("db"),
  styleLayoutPairs: forwardTo("db"),
  glasses: forwardTo("db"),
  handleSets: forwardTo("db"),
  finishes: forwardTo("db"),
  glassFamilies: forwardTo("db"),
  camingOptions: forwardTo("db"),
  glassFeatures: forwardTo("db"),
  dividedLiteTypes: forwardTo("db"),
  grilleColors: forwardTo("db"),
  transoms: forwardTo("db"),
  locationOnHouse: forwardTo("db"),
  glassAssociations: forwardTo("db"),
  doorsConnection: forwardTo("db"),
  doorCollectionsConnection: forwardTo("db"),
  doorLinesConnection: forwardTo("db"),
  styleShapesConnection: forwardTo("db"),
  sidelitesConnection: forwardTo("db"),
  styleLayoutPairsConnection: forwardTo("db"),
  glassFamiliesConnection: forwardTo("db"),
  handleSetsConnection: forwardTo("db"),
  finishesConnection: forwardTo("db"),
  camingOptionsConnection: forwardTo("db"),
  glassFeaturesConnection: forwardTo("db"),
  dividedLiteTypesConnection: forwardTo("db"),
  grilleColorsConnection: forwardTo("db"),
  transomsConnection: forwardTo("db"),
  glassAssociationsConnection: forwardTo("db"),
  glassesConnection: forwardTo("db"),
  frameProfilesConnection: forwardTo("db"),
  locationOnHousesConnection: forwardTo("db")
};

module.exports = Query;
